# Generated by Django 3.2.3 on 2021-07-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField(auto_now_add=True, null=True)),
                ('dating', models.DateField(auto_now_add=True, null=True)),
                ('people_count', models.CharField(max_length=5)),
                ('planet_count', models.CharField(max_length=5)),
                ('coment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gravity', models.CharField(max_length=99)),
                ('climate', models.CharField(max_length=99)),
                ('rotation_period', models.CharField(max_length=99)),
                ('orbital_period', models.CharField(max_length=99)),
                ('diameter', models.CharField(max_length=10)),
                ('terrain', models.CharField(max_length=99)),
                ('population', models.CharField(max_length=50)),
                ('planet_url', models.CharField(default='', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=99)),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=10)),
                ('charact_url', models.CharField(default='', max_length=99)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.planet')),
            ],
        ),
    ]
