# Generated by Django 3.2.3 on 2021-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_character_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charact_id',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='planet_id',
        ),
        migrations.AddField(
            model_name='character',
            name='charact_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
