# Generated by Django 3.2.3 on 2021-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210708_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climate',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='planet',
            name='gravity',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrain',
            field=models.CharField(max_length=99),
        ),
    ]
