# Generated by Django 3.2.3 on 2021-07-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210708_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.planet'),
        ),
    ]
